services:
  nginx:
    image: docker.io/library/nginx:latest
    container_name: nginx-compose
    ports:
      - "8081:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
    restart: always
